### PR TITLE
Hook up binary releases to Travis/AppVeyor

### PR DESCRIPTION
**Pull request by alexcrichton**
This is based on the support for cargo-vendor, but I figure this may be useful
to others!

### CODE REVIEW

**Comment by alexcrichton** [comment]
This may need some tweaking to get just right, but if it looks good I can toy around to make sure it's alright

**Comment by luser** [comment]
I had to rebase this because I bitrotted it by bumping the minimum Rust version. Sorry for letting this sit, this will be super useful, thanks! If you want to try pushing some test tags to make sure it's working feel free. Once I get your jobserver PR merged I'd like to tag a new release for real.

**Comment by luser** [comment]
This was pushed as https://github.com/mozilla/sccache/commit/3df9205609f04023de7e1abd3a254c5e3acf31d8

**Comment by alexcrichton** [comment]
👍

**Pull request closed without merging**
