### PR TITLE
fix: wrong SCCACHE_S3_USE_SSL value parse

### LINKED ISSUE #1803: [BUG] `SCCACHE_S3_USE_SSL` not working for master branch
To reproduce this, I wrote Dockerfile like this, and run with `docker build -t sccache-test --network host .`

```Dockerfile
FROM rust:latest

RUN cargo install --git https://github.com/mozilla/sccache.git sccache --no-default-features --features s3

ENV RUSTC_WRAPPER ${CARGO_HOME}/bin/sccache
ENV SCCACHE_BUCKET sccache
ENV SCCACHE_REGION us-east-1
ENV SCCACHE_S3_USE_SSL false
ENV AWS_ACCESS_KEY_ID minioadmin
ENV AWS_SECRET_ACCESS_KEY minioadmin
ENV SCCACHE_ENDPOINT http://localhost:9000

WORKDIR /src

RUN cargo new --bin sccache-test && \
    cd sccache-test && \
    echo 'fn main() { println!("Hello, world!"); }' > src/main.rs \
    && cargo build --release
```

And got this error:
<details>

```shell
------                                                                                                                                                                                                                             
 > [4/4] RUN cargo new --bin sccache-test &&     cd sccache-test &&     echo 'fn main() { println!("Hello, world!"); }' > src/main.rs     && cargo build --release:                                                                
#0 0.847      Created binary (application) `sccache-test` package                                                                                                                                                                  
#0 1.249 error: failed to run `rustc` to learn about target-specific information                                                                                                                                                   
#0 1.249                                                                                                                                                                                                                           
#0 1.249 Caused by:                                                                                                                                                                                                                
#0 1.249   process didn't exit successfully: `/usr/local/cargo/bin/sccache rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 2)
#0 1.249   --- stderr
#0 1.249   sccache: error: Server startup failed: cache storage failed to read: Unexpected (temporary) at read => send async request
#0 1.249 
#0 1.249   Context:
#0 1.249       url: https://localhost:9000/sccache/.sccache_check
#0 1.249       called: http_util::Client::send_async
#0 1.249       service: s3
#0 1.249       path: .sccache_check
#0 1.249       range: 0-
#0 1.249 
#0 1.249   Source: error sending request for url (https://localhost:9000/sccache/.sccache_check): error trying to connect: received corrupt message of type InvalidContentType
#0 1.249 
#0 1.249   Caused by:
#0 1.249       0: error trying to connect: received corrupt message of type InvalidContentType
#0 1.249       1: received corrupt message of type InvalidContentType
#0 1.249 
#0 1.249   Stack backtrace:
#0 1.249      0: <unknown>
#0 1.249      1: <unknown>
#0 1.249      2: <unknown>
#0 1.249      3: <unknown>
#0 1.249      4: <unknown>
#0 1.249      5: <unknown>
#0 1.249      6: <unknown>
#0 1.249      7: <unknown>
#0 1.249      8: <unknown>
#0 1.249      9: <unknown>
#0 1.249     10: <unknown>
#0 1.249     11: <unknown>
#0 1.249     12: <unknown>
#0 1.249     13: <unknown>
#0 1.249     14: <unknown>
#0 1.249     15: <unknown>
#0 1.249     16: <unknown>
#0 1.249     17: <unknown>
#0 1.249     18: <unknown>
#0 1.249     19: <unknown>
#0 1.249     20: <unknown>
#0 1.249     21: __libc_start_main
#0 1.249     22: <unknown>
#0 1.249 
#0 1.249   Run with SCCACHE_LOG=debug SCCACHE_NO_DAEMON=1 to get more information
```
</details>

With error context `url: https://localhost:9000/sccache/.sccache_check`, looks like env `SCCACHE_S3_USE_SSL=false` not working

### PR DESCRIPTION
**Pull request by DCjanus**
close #1803

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]
Thanks!

**Comment by Xuanwo** [comment]
cc @DCjanus, some of our tests are failed, can you help fix them?

**Comment by sylvestre** [comment]
Oh, sorry for the merge then

**Comment by DCjanus** [comment]
> some of our tests are failed, can you help fix them?

I will do my best to fix this issue within the coming week.

**Pull request merged**
