### PR TITLE
Support msvc as the host compiler for nvcc

### PR DESCRIPTION
**Pull request by robertmaynard**
To support MSVC as the nvcc host compiler we need to pass `-EP` for the pre-processing step. If we pass `-P` the pre-processor will place the output in `<input_file>.i` and not the requested output file given by `-o`.

### CODE REVIEW

**Comment by robertmaynard** [comment]
I believe that the link issues reported in https://github.com/mozilla/sccache/issues/1077 will be fixed with this PR. Since the pre-processor output is empty, each object file is empty and when you go to link you will get missing symbol errors.

**Comment by sylvestre** [comment]
is it possible to add the test?
thanks

**Comment by robertmaynard** [comment]
@sylvestre does that test look reasonable?

**Comment by sylvestre** [comment]
Sorry I missed your response

**Comment by robertmaynard** [comment]
Closed as https://github.com/mozilla/sccache/pull/1889 combines these changes with support for nvc++ which required a better design for how we track the host compiler mode for `nvcc`.

**Comment by sylvestre** [comment]
oh, sorry, i was afraid you were pissed :p sorry

**Pull request closed without merging**
