### PR TITLE
Update actions/checkout from v1 to v2

### PR DESCRIPTION
**Pull request by emabrey**
Extremely simple commit to update the version of the checkout action in Github CI runner.

### CODE REVIEW

**Comment by emabrey** [comment]
I'm a bit confused on how changing a CI config file modified the code coverage percentages...  I guess there is some kind of non-determinism at play like some kind of optimizer or something. Whatever, I'll take a 0.12% increase I guess 😎 .

**Comment by mitchhentges** [comment]
Makes sense to me, thanks!

**Comment by emabrey** [comment]
Between the making of this commit and the merge of it, they released v3 of the plugin. I plan to leave it at v2 though for now. The v3 plugin changeset only seems to include an update to use a more recent version of the Node runtime, which isn't exactly worth it to go bleeding edge.

**Comment by mitchhentges** [comment]
Yeah, makes sense, I saw that v3 was released a few hours before I landed this PR.
I don't think that there's harm in letting it mature a bit before we adopt it.

**Pull request merged**
