### PR TITLE
Add support for '-fdebug-compilation-dir'

### PR DESCRIPTION
**Pull request by hferreiro**

### CODE REVIEW

**Comment by luser** [comment]
Hi, thanks for the patch! First of all, the CI failures are due to:
> thread '<unnamed>' panicked at '-fprofile-instr-generate can't precede -fdebug-compilation-dir', src/compiler/args.rs:519:13

The arguments in the list need to be sorted, and the new argument is not in the right spot.

However, I have a more fundamental question--given that you're not adding code to do anything with this argument, what does this buy us? We should already handle unknown arguments, they just get passed along to the compiler.  The list is for arguments that need special handling.

**Comment by hferreiro** [comment]
Without this patch I'm getting the following in the logs:
```
parse_arguments: CannotCache(Can't handle UnknownFlag arguments with -Xclang)
```
The same happens with https://github.com/mozilla/sccache/pull/349 and https://github.com/mozilla/sccache/issues/350.

Both `icecc` and `ccache` have no extra code for handling `Xclang` parameters, besides `-load`. What is different in `sccache`?

**Comment by hferreiro** [comment]
Hey @luser, can you provide some input on my last comment?

**Comment by luser** [comment]
> Both icecc and ccache have no extra code for handling Xclang parameters, besides -load. What is different in sccache?

Hm, I'm not actually sure why things are implemented this way. I know we have two-pass parsing to handle the set of `-Xclang` parameters (most specially for clang-cl where they're totally different). I'm going to merge this PR, feel free to open an issue on handling this more gracefully in the general case.

**Pull request merged**
