### PR TITLE
 Add authentication to S3 GET requests 

### PR DESCRIPTION
**Pull request by Marwes**
This is configurable through the `SCCACHE_S3_GET_AUTH` environment variable or the `get_auth` in the S3 config. When `"true"`, authentication will be performed in the same manner as for PUT requests, allowing completely private buckets to be used.

Based on and closes #135

### CODE REVIEW

**Comment by Marwes** [comment]
Ping @luser

**Comment by luser** [comment]
I was on vacation last week and I'm at a company All-Hands this week so I might not get to handling sccache pull requests right away. Sorry for the delay!

**Comment by rbsheth** [comment]
Ping @luser. Waiting on this to start adopting sccache in my workflow.

**Comment by Marwes** [comment]
Rebased. Would like to see this merged but I don't know who is maintaining this now.

**Comment by spease** [comment]
This is from jrobsonchase:s3_get_auth? Then I suppose I'm on the team that inherited this code. Would be nice to see it merged in so we don't have to keep around an internal repository for it.

**Comment by Marwes** [comment]
> This is from jrobsonchase:s3_get_auth?

Yep, I think the authorship of those commits got lost in a rebase however :/

**Comment by Marwes** [comment]
@glasah Fixed the typo!

**Comment by mihaiplesa** [comment]
Looking forward for this to get in.

**Pull request closed without merging**
