### PR TITLE
ci: Add integration test for redis

### PR DESCRIPTION
**Pull request by Xuanwo**
This PR will add integration tests for redis

### CODE REVIEW

**Comment by Xuanwo** [comment]
```
shogo82148/actions-setup-redis@v1 is not allowed to be used in mozilla/sccache. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, or matching the following: !/mozilla/**, !mozilla/**, ./**, 10up/wpcs-action@*, aws-actions/*, docker/*, pypa/gh-action-pypi-publish@v1.4.2, slackapi/slack-github-action@*, google-github-actions/*, erlef/setup-beam@v1, yesolutions/mirror-action@*, codecov/codecov-action@*, tj-actions/changed-files@*, tj-actions/glob@*, vmactions/freebsd-vm@v0, actions-rs/toolchain@v1, shivammathur/setup-php@*, EmbarkStudios/*.
```

Hi, @sylvestre, I want to use action `shogo82148/actions-setup-redis@v1`.

**Comment by sylvestre** [comment]
I will ask my colleagues at Mozilla but it might take a week or two

**Comment by Xuanwo** [comment]
> I will ask my colleagues at Mozilla but it might take a week or two

Ok, maybe it's better to avoid using new actions here. Let's use github native service feature.

**Comment by sylvestre** [comment]
if you could, would be great indeed :)

**Comment by Xuanwo** [comment]
cc @sylvestre, this PR is ready for review now!

**Comment by sylvestre** [comment]
Fails with
```
Run /home/runner/.cargo/bin/sccache --show-stats | grep redis --passthru
grep: unrecognized option '--passthru'
```

**Comment by Xuanwo** [comment]
> Fails with
> 
> ```
> Run /home/runner/.cargo/bin/sccache --show-stats | grep redis --passthru
> grep: unrecognized option '--passthru'
> ```

Fixed

**Comment by sylvestre** [comment]
it would be nice to do a second build to verify that
`Cache hits` isn't at 0 ?

**Comment by sylvestre** [comment]
This is terrific. I wonder if we should not replicate this for other services
wdyt?

**Pull request merged**
