### PR TITLE
Exit when increment_compilation is enabled.

### LINKED ISSUE #1596: Trigger an error if rust incremental enabled
Sccache cannot cache incremental builds, it is better to throw an error if it is not disabled. We can do this before sccache is started.

Ref: https://github.com/risingwavelabs/risingwave/pull/7838

### PR DESCRIPTION
**Pull request by infdahai**
fixes #1596

### CODE REVIEW

**Comment by sylvestre** [comment]
nice, thanks!

**Comment by drahnr** [comment]
Do we want to remove the env and print a warning rather than terminating?

**Comment by devyn** [comment]
The message as it is was rather confusing for me as I didn't even know I had CARGO_INCREMENTAL set, and I wasn't sure what it was referring to.

I think it would be better if it specifically mentioned that environment variable.

**Comment by tetigi** [comment]
A few complaints regarding this MR:

- builds that previously worked (albeit without `sccache` doing anything due to being incremental) now just totally fail. This is a fundamental behaviour change that feels like it should be behind more than just a minor version bump. 
- the error message is not clear about why it _used_ to work, but no longer does
- the error message is poorly formatted

At the very least, this feels like it should have been a `minor` version bump rather than just a patch from `0.5.0` to `0.5.1` - the behaviour is _fundamentally_ different to how it was before, with no option to opt in or out.

**Pull request merged**
