### PR TITLE
gcc: Fix rewrite_includes_only support with gcc.

### LINKED ISSUE #636: sccache-dist still not working right with gcc
While trying to build anything with `sccache gcc`, like this:

```
$ sccache /usr/bin/gcc -std=gnu99 -c t.c
```

(Where t.c is just `int main() {}`)

I get:

```
cc1: error: no include path in which to search for stdc-predef.h
<built-in>: warning: "__STDC__" redefined
<built-in>: note: this is the location of the previous definition
<built-in>: warning: "__STDC_VERSION__" redefined
<built-in>: note: this is the location of the previous definition
<built-in>: warning: "__STDC_UTF_16__" redefined
<built-in>: note: this is the location of the previous definition
<built-in>: warning: "__STDC_UTF_32__" redefined
<built-in>: note: this is the location of the previous definition
<built-in>: warning: "__STDC_HOSTED__" redefined
<built-in>: note: this is the location of the previous definition
Compiler killed by signal 1
```

Relevant bits from the sccache log:

<details>

```
TRACE 2020-01-12T20:58:38Z: sccache::cmdline: parse
DEBUG 2020-01-12T20:58:38Z: sccache::config: Attempting to read config file at "/home/emilio/.config/sccache/config"
TRACE 2020-01-12T20:58:38Z: sccache::commands: Command::StartServer
Starting sccache server...
TRACE 2020-01-12T20:58:38Z: sccache::commands: run_server_process
TRACE 2020-01-12T20:58:38Z: sccache::cmdline: parse
DEBUG 2020-01-12T20:58:38Z: sccache::config: Attempting to read config file at "/home/emilio/.config/sccache/config"
TRACE 2020-01-12T20:58:38Z: sccache::commands: Command::InternalStartServer
 INFO 2020-01-12T20:58:38Z: sccache::server: start_server: port: 4226
 INFO 2020-01-12T20:58:38Z: sccache::server: Enabling distributed sccache to https://sccache1.corpdmz.ber3.mozilla.com/
DEBUG 2020-01-12T20:58:38Z: sccache::config: Attempting to read config file at "/home/emilio/.config/sccache/cached-config"
TRACE 2020-01-12T20:58:38Z: sccache::dist::cache: Using TcCache("/home/emilio/.cache/sccache-dist-client/client/tc", 1073741824)
 INFO 2020-01-12T20:58:38Z: sccache::server: Successfully created dist client with 140 cores across 6 servers
 INFO 2020-01-12T20:58:38Z: sccache::cache::cache: No configured caches successful, falling back to default
TRACE 2020-01-12T20:58:38Z: sccache::cache::cache: Using DiskCache("/home/emilio/.cache/sccache", 10737418240)
 INFO 2020-01-12T20:58:38Z: sccache::server: server started, listening on port 4226
DEBUG 2020-01-12T20:58:38Z: sccache::server: notify_server_startup(Ok { port: 4226 })
TRACE 2020-01-12T20:58:45Z: sccache::server: incoming connection
TRACE 2020-01-12T20:58:45Z: sccache::server: handle_client
DEBUG 2020-01-12T20:58:45Z: sccache::server: handle_client: compile
TRACE 2020-01-12T20:58:45Z: sccache::server: compiler_info
TRACE 2020-01-12T20:58:45Z: sccache::server: compiler_info cache miss
TRACE 2020-01-12T20:58:45Z: sccache::compiler::compiler: detect_compiler: /usr/bin/gcc
TRACE 2020-01-12T20:58:45Z: sccache::compiler::compiler: detect_c_compiler
TRACE 2020-01-12T20:58:45Z: sccache::compiler::compiler: compiler Some("/usr/bin/gcc" "-E" "/tmp/sccache.H7whX5yzPAZ7/testfile.c")
DEBUG 2020-01-12T20:58:45Z: sccache::compiler::compiler: Found GCC
DEBUG 2020-01-12T20:58:45Z: sccache::server: check_compiler: Supported compiler
DEBUG 2020-01-12T20:58:45Z: sccache::server: parse_arguments: Ok: ["-std=gnu99", "-c", "t.c"]
DEBUG 2020-01-12T20:58:45Z: sccache::compiler::compiler: [t.o]: get_cached_or_compile: ["-std=gnu99", "-c", "t.c"]
TRACE 2020-01-12T20:58:45Z: sccache::compiler::gcc: preprocess
TRACE 2020-01-12T20:58:45Z: sccache::compiler::gcc: preprocess: Some("/usr/bin/gcc" "-x" "c" "-E" "-fdirectives-only" "t.c" "-std=gnu99")
TRACE 2020-01-12T20:58:45Z: sccache::compiler::c: [t.o]: Preprocessor output is 14616 bytes
TRACE 2020-01-12T20:58:45Z: sccache::util: Hashed 0 files in 0.014 s
DEBUG 2020-01-12T20:58:45Z: sccache::compiler::compiler: [t.o]: generate_hash_key took 0.014 s
TRACE 2020-01-12T20:58:45Z: sccache::compiler::compiler: [t.o]: Hash key: ba41e1cac5949b53b3f8d3508e5d4fc8ef44634354e94b0c36345daeb7d9ea565a4b3b2a9e1e9f96188e2369125be592eadc78651b222dbf16b1dabb8351e149
TRACE 2020-01-12T20:58:45Z: sccache::cache::disk: DiskCache::get(ba41e1cac5949b53b3f8d3508e5d4fc8ef44634354e94b0c36345daeb7d9ea565a4b3b2a9e1e9f96188e2369125be592eadc78651b222dbf16b1dabb8351e149)
TRACE 2020-01-12T20:58:45Z: sccache::cache::disk: DiskCache::get(ba41e1cac5949b53b3f8d3508e5d4fc8ef44634354e94b0c36345daeb7d9ea565a4b3b2a9e1e9f96188e2369125be592eadc78651b222dbf16b1dabb8351e149): FileNotInCache
DEBUG 2020-01-12T20:58:45Z: sccache::compiler::compiler: [t.o]: Cache miss in 0.000 s
TRACE 2020-01-12T20:58:45Z: sccache::compiler::gcc: compile
DEBUG 2020-01-12T20:58:45Z: sccache::compiler::compiler: [t.o]: Attempting distributed compilation
DEBUG 2020-01-12T20:58:45Z: sccache::compiler::compiler: [t.o]: Creating distributed compile request
TRACE 2020-01-12T20:58:45Z: sccache::compiler::c: Dist inputs: "t.c"
DEBUG 2020-01-12T20:58:45Z: sccache::compiler::compiler: [t.o]: Identifying dist toolchain for "/usr/bin/gcc"
DEBUG 2020-01-12T20:58:45Z: sccache::dist::cache::client: Weak key /usr/bin/gcc-285a9347584933bd8686cf3c03e6407b926e57e2fa4ca60e58126c535034ce20dd579ecf372d8e5176c4c9271cf46625ce247955adb4b73e3ecd492339f70dfb appears to be new
 INFO 2020-01-12T20:58:45Z: sccache::compiler::c: Generating toolchain /usr/bin/gcc
DEBUG 2020-01-12T20:58:45Z: sccache::compiler::c: find named prog as output:
as

===

DEBUG 2020-01-12T20:58:45Z: sccache::compiler::c: find named prog objcopy output:
objcopy

===

DEBUG 2020-01-12T20:58:45Z: sccache::compiler::c: find named prog cc1 output:
/usr/libexec/gcc/x86_64-redhat-linux/9/cc1

===

DEBUG 2020-01-12T20:58:45Z: sccache::compiler::c: find named prog cc1plus output:
/usr/libexec/gcc/x86_64-redhat-linux/9/cc1plus

===

DEBUG 2020-01-12T20:58:45Z: sccache::compiler::c: find named file specs output:
specs

===

DEBUG 2020-01-12T20:58:45Z: sccache::compiler::c: find named file liblto_plugin.so output:
liblto_plugin.so

===

DEBUG 2020-01-12T20:58:48Z: sccache::compiler::compiler: [t.o]: Requesting allocation
 INFO 2020-01-12T20:58:48Z: sccache::dist::http::client: Need to request new certificate for server 10.238.24.17:10500
DEBUG 2020-01-12T20:58:48Z: sccache::compiler::compiler: [t.o]: Sending toolchain 3338609dc88f7144525529fa602ed3e2d3dca3dcd2013be093956271d0811f9dc5567ecf2258ffda9871242326dd1d486ffb0a1ba4214d0a89443b006cac8133 for job 380375
DEBUG 2020-01-12T20:58:48Z: sccache::compiler::compiler: [t.o]: Running job
TRACE 2020-01-12T20:58:48Z: sccache::dist::http::client: Compressed inputs from 16384 -> 4658
 INFO 2020-01-12T20:58:49Z: sccache::compiler::compiler: fetched []
DEBUG 2020-01-12T20:58:49Z: sccache::compiler::compiler: [t.o]: Compiled but failed, not storing in cache
TRACE 2020-01-12T20:58:49Z: sccache::server: CompileFinished retcode: signal: 1
```

</details>

cc @froydnj

### PR DESCRIPTION
**Pull request by emilio**
Fixes #636.

With this I'm able to get an sccache-dist build with gcc.

### CODE REVIEW

**Comment by froydnj** [comment]
Why do we not want to modify https://github.com/mozilla/sccache/blob/2bf971b7878d98d96ed037bff634d332e3c53f51/src/compiler/gcc.rs#L479-L489 ?

**Comment by emilio** [comment]
Why would we need to modify that? You cannot pass `-fpreprocessed` to that, the `-E -fdirectives-only` pass is the one that takes care of preprocessing it.

**Comment by emilio** [comment]
So to clarify, the way we compile right now a single C++ file is (simplified of course):

## With `rewrite_includes_only=false`

 * `g++ -x c++ -E` to generate the preprocessed output then
 * `g++ -x c++-cpp-output`

This is fundamentally fine, since `-x c++-cpp-output` avoids trying to preprocess the file again etc.

## With `rewrite_includes_only=true` (the problematic case)

 * `g++ -x c++ -E -fdirectives-only`, to generate the preprocessed input, then
 * `g++ -x c++`

This is _not_ fine, it has the problem that the second invocation tries to include built-in headers, etc. We need to use `-fpreprocessed -fdirectives-only` to avoid that per the documentation (and this is what distcc / icecream does too).

After this patch the `rewrite_includes_only=false` also would include `-fpreprocessed`. that's fine and seemed clear, but I could remove it if you want.

**Comment by froydnj** [comment]
Thanks for the explanation!

**Pull request merged**
