### PR TITLE
bump dependencies and affiliated minor code changes due to API changes

### PR DESCRIPTION
**Pull request by drahnr**
Extraction from #666

### CODE REVIEW

**Comment by froydnj** [comment]
It looks like this is OK up until the point that lockfile changes got committed?

**Comment by drahnr** [comment]
turned out to be a lot more grunt work than expected, happy to receive some feedback

**Comment by drahnr** [comment]
Inlcudes changes of #537

**Comment by drahnr** [comment]
@froydnj should be ready for inclusion

**Comment by froydnj** [comment]
Timeout test failures seem to be intermittent, but this now conflicts with other changes that have landed.  Please fix those up.

**Comment by drahnr** [comment]
@froydnj  rebased

**Comment by froydnj** [comment]
Looks like there are some CI errors related to the `ring` crate.

**Comment by drahnr** [comment]
Fixed

**Comment by drahnr** [comment]
please merge this _after_ #666

**Comment by drahnr** [comment]
@chmanchester @ry the apple CI keeps failing sporadically, this time it didn't even start: https://travis-ci.org/github/mozilla/sccache/builds/665235257?utm_source=github_status&utm_medium=notification

**Comment by drahnr** [comment]
Should be ready for merge

**Comment by glandium** [comment]
I think everything in here is covered with current master, except for
https://github.com/mozilla/sccache/pull/683/commits/ba3e8b12136facc32aef01154b12fa902f7868a3
I'm going to close this PR, please open a new one for that part if you think it's worth it.

**Pull request closed without merging**
