### PR TITLE
snap: disable store uploads from CI

### PR DESCRIPTION
**Pull request by Saviq**
It doesn't work for PRs from forks, which is most common in this repository.

### CODE REVIEW

**Comment by drahnr** [comment]
I don't quite understand? Why would we disable it for the main repository for the sake of making it work for a fork? You could equally create a new snapcraft account or patch your fork.

Could you please elaborate?

**Comment by Saviq** [comment]
> I don't quite understand? Why would we disable it for the main repository for the sake of making it work for a fork? You could equally create a new snapcraft account or patch your fork.

It's not for the sake of making it work for a fork. Access to secrets is limited to in-repo PRs, and most of the pull requests here originate from forks (for which the publishing was disabled already by means of the `github.repository == github.event.pull_request.head.repo.full_name` condition).

That's similar to what @Xuanwo suggested (no need for a new step, that's what the `publish` input is for). But together with @sylvestre we thought it's not worth it since most PRs will be coming from forks. I'm happy to be convinced otherwise, but can't do anything more - someone would need to set the `SNAPCRAFT_TOKEN` secret as discussed above, and this PR can be closed.

**Comment by sylvestre** [comment]
@Saviq i added SNAPCRAFT_TOKEN 
how can i share it works ? thanks :)

**Comment by Saviq** [comment]
@sylvestre try restarting this:

https://github.com/mozilla/sccache/actions/runs/5142969257/jobs/9257385196

When it succeeds, the built snap will be published under `edge/pr1764`.

**Comment by sylvestre** [comment]
and it worked, thanks :)

**Comment by Saviq** [comment]
In that case!

**Pull request closed without merging**
