### PR TITLE
Validate server started on the correct port

### PR DESCRIPTION
**Pull request by sum12**
The patch implements the TODO mentioned.

The server writes the port of on which it is listening to the socket
placed at SCCACHE_STARTUP_NOTIFY.  This port should match the port
expected by the client that requested the startup.

### CODE REVIEW

**Comment by froydnj** [comment]
Thanks!

**Comment by sum12** [comment]
Thanks for merging. There are quite a few TODO's. I would like to work on them. 
Just practicing some rust and this is a cool project. And I have some experience with ccache.
What do you think ?

**Comment by froydnj** [comment]
Fixing TODOs sounds like a great idea!

**Comment by philn** [comment]
Seems like this is causing #824

**Pull request merged**
