### PR TITLE
Use RustCrypto crates

### PR DESCRIPTION
**Pull request by newpavlov**
This PR replaces `rust-crypto` and `ring` with RustCrypto crates. Both are overkill for just HMAC and hash functions, and were duplicating each other.

### CODE REVIEW

**Comment by luser** [comment]
One thing I'd like to see is a comparison of the SHA-512 hash speed between these crates. ring has an implementation written in assembly so it's very fast. sccache spends a lot of time calculating SHA-512 hashes, so it's pretty important.

**Comment by luser** [comment]
Unrelated, but hello from [a different town named Moscow](https://en.wikipedia.org/wiki/Moscow,_Pennsylvania). :)

**Comment by newpavlov** [comment]
On my PC it's 170 MB/s vs. 260 MB/s in favour of `ring`. `sha2` has also `asm` feature, but currently it uses less optimized assembly. (we have plans to improve performance, but currently it's not top of my list) If hashing speed is important how about migrating to BLAKE2? On my PC BLAKE2b from `blake2` crate with enabled optimization features results in 615 MB/s and in 508 MB/s without them.

>hello from a different town named Moscow. :)

Hi! ;)

**Comment by luser** [comment]
Changing the hash function is more invasive because it invalidates all existing caches, but it could be done. ([we switched from SHA-1 to SHA-512 a while ago](https://github.com/mozilla/sccache/issues/108)). I can't recall if there was a reason we didn't go with BLAKE2 when we did that. @alexcrichton: you mentioned blake2b in that issue but we decided to go with SHA-512 and I don't see that we ever mentioned why we chose not to use blake2b.

**Comment by alexcrichton** [comment]
I think it may have been that [in local testing](https://github.com/mozilla/sccache/issues/108#issuecomment-296025690) it was as fast as sha-512, but that may have changed over time! I basically just went with the fastest one that was somewhat secure for this use case

**Comment by newpavlov** [comment]
So should I change hash function to BLAKE2b, revert SHA-256 implementation to ring, or leave as-is for now?

 BTW note that some modern CPUs have support for [SHA instructions](https://en.wikipedia.org/wiki/Intel_SHA_extensions), with which you can [achieve](https://crypto.stackexchange.com/questions/50618/how-fast-can-a-sha-256-implementation-go) 2 GB/s. I plan to use them in future in SHA crates. (it's not that difficult, but essentially blocked on lack of hardware on which I could test it)

**Comment by luser** [comment]
> So should I change hash function to BLAKE2b, revert SHA-256 implementation to ring, or leave as-is for now?

I don't have an immediate answer here--I'm open to a compelling argument. We should ensure that this doesn't break anything after all the sccache-dist work has landed (https://github.com/mozilla/sccache/pull/323 should be the second-to-last PR for that).

**Comment by xen0n** [comment]
Hi, is there any more interest in getting this merged? I'd like to setup `sccache` on MIPS machines, but `ring` currently doesn't build on MIPS. I'm pretty sure porters of other niche architectures would appreciate this effort, too.

**Comment by newpavlov** [comment]
I can update this PR after the decision will be made.

@chmanchester
Can you help here?

**Comment by apriori** [comment]
On the topic of hash functions performance:

https://github.com/rurban/smhasher

**Comment by q66** [comment]
This would help me significantly as well, as ring doesn't work on 64-bit or 32-bit powerpc (I at one point wrote a complete ppc64+ppc64le implementation, but ppc seemed trickier and not easily possible to implement completely, and I stopped having time to comply with the ring author's requirements of getting it upstreamed)

Fundamentally, I think relying on any (especially crypto) library that has assembly-only implementations with no fallbacks is hardly ideal, and in case of especially crypto, also irresponsible.

**Comment by newpavlov** [comment]
Looks like all changes already landed as part of other PRs. :)

**Pull request closed without merging**
