### PR TITLE
Upgrade of jsonwebtoken to version 9

### PR DESCRIPTION
**Pull request by sylvestre**
Closes: #1442
should unbreak the build on s390x

### CODE REVIEW

**Comment by Xuanwo** [comment]
Jsonwebtoken has raised its MSRV to 1.67:

https://github.com/Keats/jsonwebtoken/blob/master/Cargo.toml#L13

**Comment by sylvestre** [comment]
we are currently at 1.65. Maybe we should too
@robertmaynard any objection to upgrade rustc ?

**Comment by drahnr** [comment]
> we are currently at 1.65. Maybe we should too @robertmaynard @drahnr any objection to upgrade rustc ?

No objections.

**Comment by Xuanwo** [comment]
I recently attempted to upgrade jsonwebtoken in opendal, but it was unsuccessful. The upgrade would push ring to 0.17, a version not yet broadly supported, particularly by rustls. Perhaps we should delay the upgrade until our ecosystem is up-to-date?

**Comment by Xuanwo** [comment]
> Do you have a definition of "our ecosystem is up-to-date" ? :)

I will use `rustls` and `reqwest` as symbols. How about waiting for a new release about rustls and reqwest?

**Comment by aroberts87** [comment]
Hey all 👋🏻 ! Just fyi, `rustls` just released a few hours ago and contains the ring version bump we need here. ([link](https://github.com/rustls/rustls/releases/tag/v%2F0.21.8))

**Comment by liushuyu** [comment]
This pull request has been superseded by 0ef1a54028e252bb52b8901ad95b773327216c47

**Comment by Xuanwo** [comment]
Let's closing.

**Pull request closed without merging**
