### PR TITLE
fix: clippy warnings

### PR DESCRIPTION
**Pull request by Danielmelody**
An automatically fix by running `cargo clippy --fix`. Not sure whether worth doing it seems no one running it before.

### CODE REVIEW

**Comment by sylvestre** [comment]
Cool
Could you please fix the rustfmt warning?

And could you please enable this warning in the ci? :)

**Review by drahnr — APPROVED** [review]
Reducing the visual load by operator removal is always a plus! Thank you!

**Comment by sylvestre** [comment]
@Danielmelody ping ?

**Comment by Danielmelody** [comment]
Sorry for the late response, apparently I miss a comment from @sylvestre . But I will try to make other contributions.

**Pull request merged**
