### PR TITLE
feat: Use profile-generate to replace outdated -Zprofile options

### PR DESCRIPTION
**Pull request by Xuanwo**
Related to https://github.com/mozilla/grcov/issues/1240

I start this PR to fix the main branch's CI failure, but find out that we need to use profile-generate to replace outdated -Zprofile options.

Refer https://doc.rust-lang.org/rustc/profile-guided-optimization.html for more information.

### CODE REVIEW

**Comment by Xuanwo** [comment]
cc @sylvestre would you like to take a look? This PR will address the failing CI on main.

**Comment by Xuanwo** [comment]
Snap workflow has been disable since it never works.

**Comment by sylvestre** [comment]
thanks !

**Comment by glandium** [comment]
I think we should revert this change because:
- It broke support for command lines that contain any other -Z flag
- It broke support for -Zprofile, which may still be used with older version of rustc
- It tracks a profraw file that is irrelevant: it would be the equivalent to gcda, not gcno. And actually it never exists, because even when the program is run and a profraw file is generated, its name is different.

**Comment by Xuanwo** [comment]
Hi, I reviewed all the documentation for [Instrumentation-based Code Coverage](https://doc.rust-lang.org/rustc/instrument-coverage.html#instrumentation-based-code-coverage) and [Profile-guided Optimization](https://doc.rust-lang.org/rustc/profile-guided-optimization.html#profile-guided-optimization) and now understand the mistake pointed out by @glandium. (Thank you for that!) I’m currently working on it and will restore everything back to normal.

**Pull request merged**
