### PR TITLE
bump rust-version to 1.67 (was 1.65)

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Review by drahnr — APPROVED** [review]

**Comment by sylvestre** [comment]
@Saviq do you know how to upgrade the rustc version in snap?
I am getting:
`2023-10-18 20:07:03.279 :: 2023-10-18 20:07:02.756 ::   package `sccache v0.5.4 (/root/parts/sccache/build)` cannot be built because it requires rustc 1.67.1 or newer, while the currently active rustc version is 1.66.1
`
thanks

**Comment by Saviq** [comment]
@sylvestre this should do:

```diff
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -32,6 +32,7 @@ apps:
 parts:
     sccache:
         plugin: rust
+        rust-channel: 1.67
         source: .
         override-pull: |
           craftctl default
```

I've [asked](https://forum.snapcraft.io/t/the-rust-plugin/8588/8) for the documentation to be updated following the recent rewrite of the plugin.

**Comment by sylvestre** [comment]
@Saviq thanks but are you sure ?
I am getting:
```

2023-10-18 20:52:18.770 Bad snapcraft.yaml content:
- extra field 'rust-channel' not permitted in 'parts.sccache' configuration
```

**Comment by Saviq** [comment]
> @Saviq thanks but are you sure ?

Sorry, you'll also need:

```diff
--- a/.github/workflows/snap.yml
+++ b/.github/workflows/snap.yml
@@ -19,6 +19,7 @@ jobs:
     - name: Build and publish the snap
       uses: canonical/actions/build-snap@release
       with:
+        snapcraft-channel: edge
         review-opts: --allow-classic
         snapcraft-token: ${{ secrets.SNAPCRAFT_TOKEN }}
         publish: ${{ github.event_name == 'pull_request' && github.repository == github.event.pull_request.head.repo.full_name }}
```

It's not yet in a stable Snapcraft release - probably why the documentation isn't updated yet…

**Pull request merged**
