### PR TITLE
Make the stats persistant by saving them to cache

### LINKED ISSUE #33: Save stats to disk
Currently the stats are only saved in-memory, so when the server shuts down they're lost. We should save them to disk like the Python sccache did. This is mostly useful for local developers, where they might expect the stats to be persistent like ccache's stats. If we do this we should also add a `--zero-stats` option to match ccache.

### PR DESCRIPTION
**Pull request by elichai**
Closes #33 
I tried making it as boilerplate in the Storage trait, but too much lifetime issues (upgrading to latest futures (if possible in mozilla?) should solve a lot of those)
 https://play.rust-lang.org/?gist=917b00ea0c752d6fa50f35965d969648

### CODE REVIEW

**Comment by froydnj** [comment]
I think that this saving would be better off being managed by something higher-level than sccache itself, since multiple instances of the `SccacheService` (e.g. different build processes on different machines) are going to be racing against each other to save their stats when e.g. saving them in S3 or a common disk cache on the network.

**Comment by luser** [comment]
I had thought about this a while ago (as evidenced by the age of #33) and figured the local sccache server would just persist it to the local config location, not the cache (which I understand is what `ccache` does). It could write out stats on a background thread (or with async I/O) on a regular basis and during shutdown and read them on startup.

**Comment by elichai** [comment]
So do you want it to save them into a file near where the config is saved or you don't want them to be saved by sccache at all?

**Comment by sylvestre** [comment]
inactive, closing.

**Comment by Danielmelody** [comment]
Saving to cache seems reasonable because it could be fully remote. Multi-users could share the real missing rate over time and machines.

**Pull request closed without merging**
