### PR TITLE
Remove usage of kernel32-sys crate

### LINKED ISSUE #439: Remove usage of kernel32-sys crate
kernel32-sys is no longer used with winapi 0.3 and should have been removed in #286.

### PR DESCRIPTION
**Pull request by lzutao**
Closes  #439

### CODE REVIEW

**Comment by froydnj** [comment]
This looks fine to me; could you please squash your commits into a single one, @lzutao ?

**Comment by lzutao** [comment]
Done.

**Comment by lzutao** [comment]
@chmanchester Could you leave a review for this PR?

**Comment by froydnj** [comment]
The CI failure is just a failure to upload, which seems harmless, and worked on a retrigger.  Thanks!

**Pull request merged**
