### PR TITLE
Zero stats if -z --zero-stats is passed on cmdline

### PR DESCRIPTION
**Pull request by flxo**
Straight forward implementation of clearing statistics when -z or --zero-stats is passed on command line.
This command also outputs the stats upon successful execution in order to provide feedback about the configured cache. The argument names are taken from `ccache`.

The stats are currently not persistent, but for testing this option appears useful to me, because I do not need to restart the server upon every testrun. Once the persistence is implemented, `sccache` should   provide a way to zero them - so take this patch as a preparation.

In order to make the patch less noisy, I'm happy to regenerate with the exact proto/protoc version used the last time, if someone can tell.

### CODE REVIEW

**Comment by luser** [comment]
Thanks! This will be more useful when https://github.com/mozilla/sccache/issues/33 gets fixed, but I agree that having this in place is desirable either way. It looks like I used protobuf 2.6.1 to generate protocol.rs in the past, and rust-protobuf 1.0.23 (I'm not sure if that's important or not).

**Comment by flxo** [comment]
I used protobuf `v1.0.19` for this update. Version `v1.0.23` showed some differences when generating on the current `master`...

**Comment by luser** [comment]
I'm actually not sure if that's the version of `rust-protobuf` I have installed, I don't know that there's any way to query the installed binaries for their version.

**Comment by luser** [comment]
Running strings on the binary leads me to believe it was compiled from rust-protobuf 1.0.21.

**Comment by flxo** [comment]
To check the installed version run `cargo install --list`.
cargo also provides a way to force a specific version during install: `cargo install --force --vers 1.0.18 protobuf`. Unfortunately the `--vers` argument is broken (at least on `cargo 0.13.0-nightly (eca9e15 2016-11-01)` that comes with `stable`):
```
~ $ cargo --version
cargo 0.13.0-nightly (eca9e15 2016-11-01)
~ $ cargo install -f --vers 1.0.19 protobuf
Updating registry `https://github.com/rust-lang/crates.io-index`
Compiling protobuf v1.0.24
...
```

On `nightly` it's fine. I did some research in `cargo` but could not find a issue of commit where this was fixed or changed. Not sure whether I searched in the right place...

I tried all version of `protobuf` down to `v1.0.13` and only `v1.0.19` did *not* show any diff in the generated output compared to the current `HEAD`.

Anyway. Shouldn't we generate with the `protobuf` version `v1.0.18` that is required in `Cargo.toml`?
When I install `v1.0.18` and regenerate I see some differences against the current `HEAD`.

How to proceed? I see the following options:

1.  Open a separate PR with a generated `protocol.rs` from `protobuf v1.0.18` and rebase this PR afterwards.
2. I can submit this patch generated with `protobuf v1.0.18`
3. Do not care too much about the `protobuf` version, because it is a subject to removed - see #20 and use `v1.0.19`. This is what I did for `fad15b8`.
4. Use the version used by @luser. Ted, could you please check your setup with `cargo install --list`?

**Comment by luser** [comment]
Thanks, TIL about `cargo install --list`! I do in fact have 1.0.21 installed:
protobuf v1.0.21:
    protobuf-bin-gen-rust-do-not-use
    protoc-gen-rust

I'm not too fussed about it, the generated protocol.rs is pretty ugly anyway, so let's just take this patch and not worry about the specific version.

**Pull request merged**
