### PR TITLE
Feature/847 allow caching multi arch builds

### PR DESCRIPTION
**Pull request by coretechsec**
Updated handling of c/c++ build commands with multiple `-arch` flags in response to https://github.com/mozilla/sccache/issues/847.

Testing has predominantly been done on macOS.

### CODE REVIEW

**Comment by sylvestre** [comment]
I guess you saw the clippy warning

**Comment by coretechsec** [comment]
> I guess you saw the clippy warning

Yeah, thanks. I think I've fixed it now

**Comment by sylvestre** [comment]
It looks great. could you please update the doc with this info ?
https://github.com/mozilla/sccache/blob/main/docs/Caching.md

**Comment by coretechsec** [comment]
> It looks great. could you please update the doc with this info ? https://github.com/mozilla/sccache/blob/main/docs/Caching.md

Updated now. Hopefully its clear enough as is but happy to tweak it.

**Comment by sylvestre** [comment]
This is great, thanks

**Comment by alcroito** [comment]
Latest 0.4.1 which includes this PR breaks multi-arch compilation that uses -Xarch flags.

https://github.com/mozilla/sccache/issues/847#issuecomment-1517546993

**Pull request merged**
