### PR TITLE
Workaround tiny_http issue #151 by disabling HTTP pipelining

### PR DESCRIPTION
**Pull request by glandium**
Instead of relying on a crate patch.

Fixes: #912

### CODE REVIEW

**Comment by glandium** [comment]
@mstange @dholbert Can you check whether a) it works properly (tests pass, which suggests it might) b) it has an impact on performance?

**Review by mitchhentges — CHANGES_REQUESTED** [review]
~`tiny-http` has the fix from [#151](https://github.com/tiny-http/tiny-http/pull/151) in release `v0.7.0`, why don't we use that release instead of working around the bug?~

Ah, that's where `rouille fits into this, my bad.

**Review by mitchhentges — APPROVED** [review]

**Review by cgsheeh — APPROVED** [review]

**Comment by dholbert** [comment]
Seems to work fine on an Ubuntu client/server/scheduler setup.

Only caveat, it doesn't seem to work when I use my Mac client (which is currently still using the latest mach-bootstrap-provided sccache version, which doesn't have this patch, if that matters).  From that client, it looks like compile jobs just hang, when the scheduler/builder are using my local build of glandium's patched revision here.

**Comment by glandium** [comment]
> Only caveat, it doesn't seem to work when I use my Mac client (which is currently still using the latest mach-bootstrap-provided sccache version, which doesn't have this patch, if that matters).

For good measure, can you check updating the mac client? (you can find a prebuild sccache in the checks tab, under artifacts)
Can you also check that build times are not much different?

**Comment by dholbert** [comment]
Yeah, I don't hit the compile-jobs-hanging issue anymore on Mac if I use the [prebuilt sccache client binary from the artifacts here](https://pipelines.actions.githubusercontent.com/xTZDbRczhQWc6twoYOC6b79HzZEBlkEMmvBunZE5uwkUcnjFFY/_apis/pipelines/1/runs/36/signedartifactscontent?artifactName=sccache-952c8b9c2ed2d8f4881f3c5b3b5814f3351e6d3f-x86_64-apple-darwin&urlExpires=2021-01-08T21%3A06%3A50.7288246Z&urlSigningMethod=HMACV1&urlSignature=GMgs7rUqm5Ff7YMWFnGwyyee2Dfq4oUNCwJWLeHerOc%3D) (instead of the one from bootstrap).

Build times don't seem to be particularly affected by this fix, in my nonscientific investigations so far; and core saturation (via `sccache --dist-status`) seems similar to what they were before too.

**Pull request merged**
