### PR TITLE
Add a snippet about logging level

### PR DESCRIPTION
**Pull request by posix4e**

### CODE REVIEW

**Comment by flxo** [comment]
Nice. For developers a hint about `SCCACHE_NO_DAEMON` might help to get started. It took me some time to find that one...

**Comment by posix4e** [comment]
@flxo Want a friendly contrinb to this PR i.ve never used NO_DAEMON

**Comment by luser** [comment]
That's sort of a leftover from development, but I agree that it can be useful for diagnosing problems. I'll tweak the documentation here and land a version of this.

**Comment by luser** [comment]
Tweaked and pushed in https://github.com/mozilla/sccache/commit/d8a28bffade1a83a08b87e7da101e7a359757eff

**Pull request closed without merging**
