### PR TITLE
Support emit pch header

### PR DESCRIPTION
**Pull request by Danielmelody**

### CODE REVIEW

**Comment by sylvestre** [comment]
would you have a bit more context? where do you see this flag? thanks

**Comment by Danielmelody** [comment]
Hmm, we are using clang/clang++ on windows(not clang-cl), and using cmake to generate pch files. The compile command cmake output is just like in the test case I wrote. Except the file name changed by real file name on my disk.

**Comment by sylvestre** [comment]
OK, could you please add these info in the commit message ?
thanks

**Comment by Danielmelody** [comment]
@sylvestre Just added a new line within commit message

**Comment by scorpion-26** [comment]
This PR/commit is a bit borked. It breaks PCH compilation when using the officially documented way of _just_ specifiying ```-c -x c++-header```(https://releases.llvm.org/3.1/tools/clang/docs/UsersManual.html#precompiledheaders). You can see a proper explanation in the addendum of my linked issue.

**Pull request merged**
