### PR TITLE
dist/cache: include paths in error contexts

### PR DESCRIPTION
**Pull request by mathstuf**
Fixes: #885

---
In the interest of helping 0.4.0 get finalized :) .

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]
Thanks for contribution, LGTM!

**Comment by sylvestre** [comment]
Would it be possible to have tests to cover these errors?

**Comment by mathstuf** [comment]
Maybe? What fs abstractions do we have available? FUSE is a possibility, but feels like a lot of code to test error paths. Also doesn't help with Windows at all.

**Comment by drahnr** [comment]
Is there a particular reason to not use `fs-err` instead?

**Comment by mathstuf** [comment]
That seemed like a wider-effecting change than the issue was asking for. And given that 0.4.0 is now "one" issue away by milestoned issues…I'd like to see 0.4.0 come out first personally.

**Pull request merged**
