### PR TITLE
Add dist-server into release assets

### PR DESCRIPTION
**Pull request by prehistoric-penguin**

### CODE REVIEW

**Comment by glandium** [comment]
It would probably be better if there was a separate dist-server asset.

**Comment by prehistoric-penguin** [comment]
> It would probably be better if there was a separate dist-server asset.

So it's suggested to closing this PR?

**Comment by glandium** [comment]
You can update your branch, it will update the PR.

**Comment by glandium** [comment]
Superseded by #902

**Comment by glandium** [comment]
It turns out I forgot one bit in #902, so it didn't work for 0.2.14... I'll make sure it works before next release.

**Comment by glandium** [comment]
Come to think of it, with the way releases are happening (a6a8becb842198e2d04302bfdacdf1c66740a7b0), and considering what that does, even if #902 had worked, the released binaries would have been useless.

**Comment by glandium** [comment]
Opened #912 to track this.

**Pull request closed without merging**
