### PR TITLE
feat: Migrate redis to opendal based

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

This PR will migrate redis to opendal based.

The `current_size` and `max_size` may not work anymore, we will address them in the future.

### CODE REVIEW

**Comment by sylvestre** [comment]
Looks good
you tested it?

**Comment by Xuanwo** [comment]
> Looks good you tested it?

opendal will make sure all services tested: https://github.com/datafuselabs/opendal/blob/main/.github/workflows/service_test_redis.yml

**Comment by sylvestre** [comment]
I was talking about sccache :)

**Comment by Xuanwo** [comment]
> I was talking about sccache :)

Not tested with sccache. Maybe I can add a one in our CI?

**Comment by sylvestre** [comment]
it would be nice indeed :)

**Comment by Xuanwo** [comment]
Wait for https://github.com/mozilla/sccache/pull/1510

**Comment by sylvestre** [comment]
I love the new integration tests, bravo :)

**Pull request merged**
