### PR TITLE
freebsd: create /opt/pot earlier

### PR DESCRIPTION
**Pull request by sylvestre**
Maybe fix issue #1529 ?

Fails later on:
  
```
  ---- test_s3_invalid_args stdout ----
  thread 'test_s3_invalid_args' panicked at 'Unexpected stderr, failed var.contains(cache storage failed to read)
  ├── var: [2023-01-08T14:17:18Z DEBUG sccache::config] Attempting to read config file at "/tmp/sccache_freebsd.IlySuoe/.config/sccache/config"
  │   [2023-01-08T14:17:18Z DEBUG sccache::config] Couldn't open config file: No such file or directory (os error 2)
  │   [2023-01-08T14:17:18Z DEBUG sccache::config] Attempting to read config file at "/tmp/sccache_freebsd.IlySuoe/.config/sccache/config"
  │   [2023-01-08T14:17:18Z DEBUG sccache::config] Couldn't open config file: No such file or directory (os error 2)
  │   sccache: error: Server startup failed: create s3 cache failed: Unexpected (temporary) at http_util::Client::send => send blocking request, source: https://s3.amazonaws.com/test: Connection Failed: tls connection init failed: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
  │   
  │   Caused by:
  │       0: https://s3.amazonaws.com/test: Connection Failed: tls connection init failed: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
  │       1: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
  └── var as str: [2023-01-08T14:17:18Z DEBUG sccache::config] Attempting to read config file at "/tmp/sccache_freebsd.IlySuoe/.config/sccache/config"
      [2023-01-08T14:17:18Z DEBUG sccache::config] Couldn't open config file: No such file or directory (os error 2)
      [2023-01-08T14:17:18Z DEBUG sccache::config] Attempting to read config file at "/tmp/sccache_freebsd.IlySuoe/.config/sccache/config"
      [2023-01-08T14:17:18Z DEBUG sccache::config] Couldn't open config file: No such file or directory (os error 2)
      sccache: error: Server startup failed: create s3 cache failed: Unexpected (temporary) at http_util::Client::send => send blocking request, source: https://s3.amazonaws.com/test: Connection Failed: tls connection init failed: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
      
      Caused by:
          0: https://s3.amazonaws.com/test: Connection Failed: tls connection init failed: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
          1: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
  
  command=`"/Users/runner/work/sccache/sccache/target/debug/sccache" "--start-server"`
  code=2
  stdout="sccache: Starting the server...\n"
  stderr="[2023-01-08T14:17:18Z DEBUG sccache::config] Attempting to read config file at \"/tmp/sccache_freebsd.IlySuoe/.config/sccache/config\"\n[2023-01-08T14:17:18Z DEBUG sccache::config] Couldn\'t open config file: No such file or directory (os error 2)\n[2023-01-08T14:17:18Z DEBUG sccache::config] Attempting to read config file at \"/tmp/sccache_freebsd.IlySuoe/.config/sccache/config\"\n[2023-01-08T14:17:18Z DEBUG sccache::config] Couldn\'t open config file: No such file or directory (os error 2)\nsccache: error: Server startup failed: create s3 cache failed: Unexpected (temporary) at http_util::Client::send => send blocking request, source: https://s3.amazonaws.com/test: Connection Failed: tls connection init failed: invalid peer certificate contents: invalid peer certificate: UnknownIssuer\n\nCaused by:\n    0: https://s3.amazonaws.com/test: Connection Failed: tls connection init failed: invalid peer certificate contents: invalid peer certificate: UnknownIssuer\n    1: invalid peer certificate contents: invalid peer certificate: UnknownIssuer\n"
  ', /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  
```

which is probably more @Xuanwo ;)

### CODE REVIEW

**Comment by Xuanwo** [comment]
Seems we don't have ca certs installed?

**Review by drahnr — APPROVED** [review]

**Comment by sylvestre** [comment]
> Seems we don't have ca certs installed?

This one ?
https://www.freshports.org/security/ca_root_nss/

**Comment by Xuanwo** [comment]
> This one ?
> https://www.freshports.org/security/ca_root_nss/

I don't know - -

I know nothing about freebsd. In linux world, we use `ca-certificates`.

**Comment by sylvestre** [comment]
Thanks. We will see if it works

**Comment by sylvestre** [comment]
let's use @grembo 's patch https://github.com/mozilla/sccache/pull/1531 :)
I have enough contributions to sccache

**Pull request closed without merging**
