### PR TITLE
replace outdated rust-crypto crate with RustCrypto/hashes

### PR DESCRIPTION
**Pull request by AnderEnder**
Issue: rust-crypto is unmaintained and outdated crate:
- https://www.reddit.com/r/rust/comments/dfm3ya/there_are_231_crates_which_might_depend_on_this/
- https://rustsec.org/advisories/RUSTSEC-2016-0005.html

Implementation: replace rust-crypto with RustCrypto crates

### CODE REVIEW

**Comment by luser** [comment]
There's an existing PR for this work that's been sitting due to some open questions: https://github.com/mozilla/sccache/pull/310

**Comment by chmanchester** [comment]
Ah, ok, I figured this would be a trivial issue for someone familiar with the rust crypto ecosystem, but I will take a deeper dive into the context in #310 and figure out what to do.

**Comment by chmanchester** [comment]
I ended up taking care of this in #570, thank you for bringing this to our attention!

**Comment by AnderEnder** [comment]
@chmanchester, why the PR was not reviewed and closed, but all changes were moved to another one?

**Comment by chmanchester** [comment]
@AnderEnder by the time I got around to testing the change I found an issue, made a fix locally, and also noticed things needed to be re-based, so it seemed easier to start over. Sorry about that, we should have gotten to this earlier.

**Pull request closed without merging**
