### PR TITLE
Add windows arm64 to the CI

### PR DESCRIPTION
**Pull request by hjyamauchi**

### CODE REVIEW

**Comment by hjyamauchi** [comment]
CC @Xuanwo

**Comment by hjyamauchi** [comment]
This is based on the discussion https://github.com/mozilla/sccache/discussions/2223

**Comment by sylvestre** [comment]
AFAIK, it is building but not running tests, am I correct?

**Comment by hjyamauchi** [comment]
I didn't realize there was a test step. So, I believe so. Do we want to enable testing?

**Comment by hjyamauchi** [comment]
AFAICT, windows arm64 runners aren't available on github yet. So testing for windows arm64 isn't currently viable?

**Comment by sylvestre** [comment]
correct but not an issue :)

**Comment by hjyamauchi** [comment]
@sylvestre Great, thank you!
Do you have an idea when the next release that includes a windows arm64 binary may happen?

**Pull request merged**
