### PR TITLE
Rm openssl pulled in linux

### PR DESCRIPTION
**Pull request by NobodyXu**
Follow up for #1737

Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Review by drahnr — APPROVED** [review]

**Comment by NobodyXu** [comment]
I've rebased against main, so this PR is now ready to merge.

**Comment by sylvestre** [comment]
Seems that it broke one of the Ubuntu test

**Comment by NobodyXu** [comment]
> Seems that it broke one of the Ubuntu test

Honestly, I have no idea why changing depdencies would break `dist_compiles`.

**Comment by NobodyXu** [comment]
Superseded by #1742

**Pull request closed without merging**
