### PR TITLE
deps: bump libc from 0.2.153 to 0.2.155

### PR DESCRIPTION
**Pull request by huajingyun01**
Update [libc](https://github.com/rust-lang/libc)  to 0.2.155.

Release notes :https://github.com/rust-lang/libc/releases

### CODE REVIEW

**Comment by sylvestre** [comment]
@huajingyun01 is there a something that you need in libc 0.2.155 ? thanks

**Comment by huajingyun01** [comment]
> @huajingyun01 is there a something that you need in libc 0.2.155 ? thanks

Hi @sylvestre  I had to update libc to 0.2.155 to support LoongArch64, because sccache compilation based on musl LoongArch64 failed.
https://github.com/rust-lang/libc/pull/3606

Thanks.

**Comment by riquito** [comment]
Hi, I received the same PR for my project tuc https://github.com/riquito/tuc/pull/151 and I just closed it because @huajingyun01 is forking multiple repositories and creating the same PRs over multiple repositories, for no clear reason

**Comment by sylvestre** [comment]
@riquito probably because Loongson has been paying developers to support the FLOSS ecosystem on this arch.
I have seen this happening in Debian too. It is legit stuff.

@huajingyun01 You might want to make it clear in your PR requests in general ;)

**Comment by huajingyun01** [comment]
> @riquito probably because Loongson has been paying developers to support the FLOSS ecosystem on this arch. I have seen this happening in Debian too. It is legit stuff.
> 
> @huajingyun01 You might want to make it clear in your PR requests in general ;)

@sylvestre  Thanks.

 I really should take the time to provide a more detailed explanation for each PR as to why I need to make such a change.

Since there are too many repositories, I used the same comment, which didn't seem sincere, sorry I overlooked that.

**Pull request merged**
