### PR TITLE
feat: Introduce the default gha version

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

This PR will introduce the default gha version.

This change has the following benefits:

- User don't need think and pick version if they don't care or don't wanna purge cache
- Give sccache a chance to purge users cache while needed (serious bug happened)

To support this change, I did following:

- Add `SCCACHE_GHA_ENABLED` as a flag
- make `SCCACHE_GHA_VERSION` an optional version.

### CODE REVIEW

**Comment by sylvestre** [comment]
@jakelee8 Do you have an opinion on this ? :)

**Comment by jakelee8** [comment]
LGTM.

**Comment by jakelee8** [comment]
The default version could include `env!("CARGO_PKG_VERSION_MAJOR")` and maybe minor to automatically change with breaking changes.

**Comment by Xuanwo** [comment]
> The default version could include `env!("CARGO_PKG_VERSION_MAJOR")` and maybe minor to automatically change with breaking changes.

Nice idea, I will add it.

**Comment by Xuanwo** [comment]
cc @sylvestre @jakelee8 all comments have been addressed, PTAL.

**Pull request merged**
