### PR TITLE
feat: Add possibility to configure key prefix (Redis, MemCached)

### PR DESCRIPTION
**Pull request by AJIOB**
* Add possibility to configure key prefix for Redis & MemCached
* Unify Redis & MemCached expiraction time
* Actualize configuration docs

### CODE REVIEW

**Comment by sylvestre** [comment]
if i understand correctly this PR, it isn't going to change the behavior of existing configurations, right?

**Comment by AJIOB** [comment]
@sylvestre, yes, you are right.

We are not change the public API. Just documenting & unifying it.

**Comment by AJIOB** [comment]
@Xuanwo, hello.

What I need to do for merging this PR?

Do we have some problems with this changes? Or I need to split it to few ones?

**Comment by Xuanwo** [comment]
Those changes LGTM! cc @sylvestre do you want to take another look?

**Comment by sylvestre** [comment]
thanks!

**Pull request merged**
