### PR TITLE
Enable clippy and fmt check in CI

### PR DESCRIPTION
**Pull request by ry**

### CODE REVIEW

**Comment by froydnj** [comment]
My experience with format checks in CI has been largely negative, and I'm not inclined to enable them for this project.  Same with clippy enforcement.

If people are inclined to run them periodically, I'm happy to check in those PRs, but I don't think it's worth bouncing your patch out of CI just because you didn't format your argument list correctly or you called `x.len() > 0` instead of `!x.is_empty()`.

**Comment by ry** [comment]
@froydnj This project had hundreds of clippy errors and compiler warnings because there is no CI check. My experience with Rust's clippy is it pushes you in the right direction, making code smaller (you can see this from my patches). Not enabling a formatting check causes more work - like here https://github.com/mozilla/sccache/pull/706#pullrequestreview-374639791

Does Mozilla allow you to commit lint errors or non-formatted code in other projects? 

There is an argument to not have these check early on in a project - but sccache has a lot of code and is used in production systems. I don't see why we wouldn't want to enforce lint (clippy) and formatting.

**Comment by froydnj** [comment]
> Does Mozilla allow you to commit lint errors or non-formatted code in other projects?

I think the JS code in Firefox is ESLint-clean (although it's possible that certain checks have been disabled there) and maybe prettier-formatted?  The Python code has lint checks enabled, but is not (yet?) formatted with something like Black (I think there are some format checks enforced via flake8?).  The C++ code is run through `clang-format` on a periodic basis (~weekly), but formatting is not enforced via CI; we do have a number of compiler warnings enabled, and warnings are errors in CI.  I think our Rust code is getting to the same point as the C++ code as far as formatting goes; I don't believe we run clippy there.

I think the plan for C++ (maybe for Rust?) is auto-format on patch submission.  That's much more palatable than CI failures for whitespace issues.

The only other Mozilla-associated projects (not run by Mozilla) I have recently contributed to are the Bytecode Alliance's Lucet and Cranelift; both of those do enforce formatting, but not clippy, IIRC.

> There is an argument to not have these checks early on in a project lifecycle - but sccache has a lot of code and is used in production systems. I don't see why we wouldn't want to enforce lint (clippy) and formatting.

My impression is that it's not a great experience for people contributing one-off or even several-off patches.  "Oh, you ran `cargo test` and everything was fine?  Sorry, you should have run all these other things too, even though your code is perfectly fine."  When it's as easy and automatic as turning on compiler warnings is locally for C/C++ projects via the normal build system, then I think it's reasonable to enforce these things in CI.

**Comment by ry** [comment]
@froydnj Given that sccache has many different conditional compilations it's quite difficult for a contributor to see that their change does not introduce lint errors. Indeed - in this PR there are more lint fixes that I wasn't previously catching. I really think there is little downside and a huge upside to enabling these. Lint and formatting in Rust are helpful. sccache needs more CI, not less. Unrelated to linting and formatting, but sccache is currently broken on windows - and has been broken for a long time. It would be helpful to contributors if they did not immediately encounter warnings and unformatted code.

**Comment by nnethercote** [comment]
See #776!

**Pull request closed without merging**
