### PR TITLE
Bump MSRV to 1.64 

### PR DESCRIPTION
**Pull request by Xuanwo**
Read more detail at https://github.com/mozilla/sccache/issues/1609

### CODE REVIEW

**Comment by Xuanwo** [comment]
freebsd tests seems always failed since https://github.com/mozilla/sccache/commit/e53407202d1e8a4d5d61d8c6f95f793826582e57

**Comment by sylvestre** [comment]
sorry, it needs to be rebased

**Comment by Xuanwo** [comment]
> sorry, it needs to be rebased

DONE

**Comment by sylvestre** [comment]
I am wondering if we should not wait after we released 0.4.0 before merging this

**Comment by Xuanwo** [comment]
> I am wondering if we should not wait after we released 0.4.0 before merging this

It's more common to bump MSRV when bumping minor releases. But both LGTM.

**Pull request merged**
