### PR TITLE
Update Cargo.lock

### PR DESCRIPTION
**Pull request by ry**
It appears to be missing the quote 1.0.2 dependency.

### CODE REVIEW

**Comment by froydnj** [comment]
Thanks!

**Comment by froydnj** [comment]
@ry apparently eed9a63 was tagged?

**Comment by ry** [comment]
@froydnj I don't understand what you're asking? Git tagged? Not from what I can see.

**Comment by ry** [comment]
Ah - I've just seen https://github.com/mozilla/sccache/releases/tag/'' ... I don't know what caused that. I don't have the tag locally.

**Pull request merged**
