### PR TITLE
Stop using icecc-create-env to build environments

### PR DESCRIPTION
**Pull request by mystor**
I mentioned to @luser that I had whipped up my own create-env system within sccache-dist, due to icecc-create-env not working well for me.

Not sure how well this works, but it can probably at least act as a starting point.

### CODE REVIEW

**Comment by jrmuizel** [comment]
review ping

**Comment by jrmuizel** [comment]
@mystor also it looks like this doesn't build.

**Comment by mystor** [comment]
Hmm - can't build it locally again due to the build system being unable to find openssl, but here's a fix hopefully(?)

**Comment by aidanhs** [comment]
This looks good to me. I've made a PR to this branch to fix the build failures at https://github.com/mystor/sccache/pull/1. It also needs a rebase, but the only conflict is a `use` line.

Alternatively, I'm happy to rebase and create a new PR.

**Comment by luser** [comment]
It looks like this needs to be rebased to latest master. Do one of you want to take care of that or should I do it?

**Comment by mystor** [comment]
If there's any chance you'd be willing to do that it would save me setting stuff up again :-)

**Comment by luser** [comment]
I rebased this locally and pushed it to master:
https://github.com/mozilla/sccache/commit/06421bafe014916d1ef232fa2857bd29c4afaad1

Thanks!

**Pull request closed without merging**
