### PR TITLE
[dist] feat/rust: blacklist support for rust builds

### PR DESCRIPTION
**Pull request by drahnr**
Tracking PR handling issues of

sense right now, the negative impact is pretty big for a config key change
- [x] issue #696 - black list for `Cargo.toml` provided `build = x.rs`
- [x] add environment and config file based configuration

~Prerequisistes: PR #666~

### CODE REVIEW

**Comment by froydnj** [comment]
FWIW, this is what I did for testing a patch for #675 solely for tests made during configure:

https://github.com/froydnj/sccache/commit/0325ae73276d2d17c9f41213525d941c99aeeef0

It is in some ways a hack, but I think it's a more elegant hack than trying to thread something through `CompilerArguments`.

**Comment by drahnr** [comment]
After a brief look, I am not sure this solves the issue - there is still the injection within `parse_arguments` which one would need for rust too, so I'd be still in favour of fiddling an `RustBlacklist` which implements `trait Blacklist` as an `Option<dyn Blacklist>` through those two `fn` layers.

**Comment by froydnj** [comment]
Sure, you’d have to do something similar for Rust as well.    I was just trying to point out what I thought might be a better way forward.

I tried to do something at the `CompilerArguments`/`generate_hash_key` layer and found myself getting very frustrated with what you have to do to make types line up and essentially having to lie about even having a hash key.  This was a much easier solution.

**Comment by drahnr** [comment]
@froydnj I'll take another look probably tomorrow how to do this with the least friction :) I really appreciate you giving code pointers and samples :+1:

**Comment by drahnr** [comment]
I don't think there is a good way of making this generic.

After all, the `BlackList` must depend on the type of the `Box<dyn Compilation>` for the compiler it tries to cache, since that contains also valid meta data to filter on.
The current approach is to make the `Blacklist` inherent to the compiler - and share it with the `Hasher` via an `Arc<_>` to avoid pointless copies.

But this also means that the common shared of blacklists will be the configuration, which frankly is also divided into the Rust/CXX(CompilerVarian) strains plus a few special case booleans.

**Comment by drahnr** [comment]
```
DEBUG 2020-04-03T07:22:30Z: sccache::compiler::rust: blacklist(rust)> blacklist matched with rule: crate name is enlisted: syn
DEBUG 2020-04-03T07:22:30Z: sccache::compiler::compiler: [syn]: generate_hash_key took 1.078 s
TRACE 2020-04-03T07:22:30Z: sccache::compiler::compiler: [syn]: Hash key: 74d4a50c23f9ec2c21dd9045c680e4451edada2fdb21b849a3af321c09b38cb5
DEBUG 2020-04-03T07:22:30Z: sccache::compiler::compiler: [syn]: Cache blacklisted in 0.000 s
TRACE 2020-04-03T07:22:30Z: sccache::compiler::rust: [syn]: compile
DEBUG 2020-04-03T07:22:30Z: sccache::compiler::compiler: [syn]: Compiling locally
```
for

```
SCCACHE_BLACKLIST_RUST_BUILD_SCRIPT=1
SCCACHE_BLACKLIST_RUST_FILES=src/lib.rs
SCCACHE_BLACKLIST_RUST_CRATES=syn
SCCACHE_BLACKLIST_RUST=crate:regex,file:src/main.rs
```

I'd appreciate a review, thanks!

**Comment by drahnr** [comment]
TODOs:
* [ ] performance measurments with `coz`/`flamegraph`
* [ ] documentation

**Comment by drahnr** [comment]
I'd like some feedback on this in what direction this should progress or not

**Comment by glandium** [comment]
I think this is superseded by #798.

**Comment by drahnr** [comment]
Not sure I quite follow, #798 mingles the logic into the hash generation which I find rather unfortunate.

**Pull request closed without merging**
