### PR TITLE
rustc driver detection - includes #1897

### LINKED ISSUE #861: Support arbitrary rustc drivers
Currently rustc and clippy-driver are hardcoded. It would be nice if arbitrary rustc drivers would be supported. This includes [`cargo-miri rustc`](https://github.com/rust-lang/miri), [`cg_clif`](https://github.com/bjorn3/rustc_codegen_cranelift) and any other program that has a rustc compatible command line interface. One way would be to first check for a C compiler and if the output is `error: Unrecognized option: 'E'` instead attempt to detect a rustc compiler.

cc https://github.com/bjorn3/rustc_codegen_cranelift/issues/1091

### PR DESCRIPTION
**Pull request by drahnr**
If we are not sure it's rustc like and we check -vV output to accept valid rustc drivers. Simplifies #1897 . 

Fixes #861

### CODE REVIEW

**Comment by sylvestre** [comment]
It would be nice to update the commit to explicit why we are doing it

**Comment by drahnr** [comment]
> It would be nice to update the commit to explicit why we are doing it

The _commit_ or the PR desc?

**Comment by sylvestre** [comment]
The commit please

**Comment by drahnr** [comment]
Is the above sufficient @sylvestre ? I'd still be in favor of squash this PR, left the two commits separate for no particular reason other than authorship

**Comment by drahnr** [comment]
The coverage report is obsolete, it actually improved marginally.

CC @sylvestre anything missing/insufficient, otherwise I'd merge?

**Pull request merged**
