### PR TITLE
Use Reqwest to access s3 to follow redirects

### LINKED ISSUE #265: S3: handle 307 Temporary Redirect
At the moment when I try to hit my S3 bucket at `http://my-bucket.s3.amazonaws.com`, I am getting a redirect
```
HTTP/1.1 307 Temporary Redirect
Location: http://my-bucket.s3.eu-west-2.amazonaws.com/
```
Apparently this [happens sometimes](https://serverfault.com/questions/730958/error-response-was-307-temporary-redirect-when-trying-to-upload-to-buck)

`sccache` doesn't seem to handle this at all, the debug log just says
```
WARN:sccache::cache::s3: Got AWS error: Error(BadHTTPStatus(TemporaryRedirect), State { next_error: None })
```
It would be nice if this was handled more gracefully - ideally transparently following the redirect, or else giving me a way to specify my region in the `SCCACHE_BUCKET` env var.

### PR DESCRIPTION
**Pull request by Marwes**
Fixes #265 

(I forgot to disable rustfmt so it unfortunately formatted the file, I can try and remove it if necessary).

### CODE REVIEW

**Comment by Marwes** [comment]
I have verified this locally by pointing sccache to a eu s3 bucket without specifying the region.

**Comment by luser** [comment]
Thanks for the patch! I'm trying to get a few large pull requests merged currently (https://github.com/mozilla/sccache/pull/274 and https://github.com/mozilla/sccache/pull/277), so this may have to wait until those merge just to avoid any rebasing headaches.

**Comment by luser** [comment]
> (I forgot to disable rustfmt so it unfortunately formatted the file, I can try and remove it if necessary).

It's not causing any merge conflicts so we'll let it ride. I should probably rustfmt the whole codebase at some point now that rustfmt is close to stable.

**Comment by luser** [comment]
Thanks again!

**Pull request merged**
